### ISSUE TITLE
" Validation error ... Member must satisfy regular expression pattern: arn:aws:iam:: ..."

### ISSUE THREAD

**Issue by gavinengel** [motdotla/node-lambda-template#1]
I'd love to be able to use your project to run Lambda functions.  Unfortunately, I'm getting stuck at the initial steps.  I'm hoping you wouldn't mind providing a hint to get me past a roadblock.

I've tried to create a AWS user, role, and policy to allow node-lambda to work.  When I try using node-lambda to deploy the node-lambda-template, I see this error:

```
[/_/Workspace/gits/node-lambda-template]$ ./node_modules/.bin/node-lambda deploy               [master] 
Generating zip file
Reading zip file to memory
Uploading zip file to AWS Lambda with parameters:
{ FunctionName: 'tutorial-development',
  FunctionZip: <Buffer 50 4b 03 04 14 00 00 00 08 00 29 17 99 46 a9 f3 94 05 8e 00 00 00 4b 01 00 00 08 00 1c 00 69 6e 64 65 78 2e 6a 73 55 54 09 00 03 cd 3a 3b 55 d1 3a 3b 55 ...>,
  Handler: 'index.handler',
  Mode: 'event',
  Role: 'lambda_basic_execution',
  Runtime: 'nodejs',
  Description: '',
  MemorySize: '128',
  Timeout: '3' }
{ [ValidationException: 1 validation error detected: Value 'lambda_basic_execution' at 'role' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:aws:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+]
  message: '1 validation error detected: Value \'lambda_basic_execution\' at \'role\' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:aws:iam::\\d{12}:role/?[a-zA-Z_0-9+=,.@\\-_/]+',
  code: 'ValidationException',
  time: Sat Apr 25 2015 03:15:57 GMT-0400 (EDT),
  statusCode: 400,
  retryable: false,
  retryDelay: 30 }
```

Here is a screenshot of my AWS setting for a user 'node-lambda' that I created for using your project:

![screenshot from 2015-04-25 03 17 47](https://cloud.githubusercontent.com/assets/523621/7332031/5d6b8fb8-eafa-11e4-9dbc-588b772b3d90.png)

Do you have any advice for me?

**Comment by motdotla** [comment]
Hi @gavinengel, What are you pasting into `AWS_ROLE`?

It should look something like this: `AWS_ROLE=arn:aws:iam::0225887334136:role/lambda_exec_role`

**Comment by gavinengel** [comment]
Great thank you.  I had to enable these Managed Policies for the role lambda_basic_execution:
- AWSLambdaBasicExecutionRole
- AWSLambdaRole

**Comment by motdotla** [comment]
Ok, :+1:

**Comment by gavinengel** [comment]
By the way, what if my node project needed to use 2 Lambda instances?  Would I need a second .env file?

**Comment by motdotla** [comment]
For now, you should setup a separate lambda node template. Treat them as separate 'apps'.

**Comment by pestir** [comment]
great

**Comment by yumikohey** [comment]
https://stackoverflow.com/questions/36741955/why-does-the-aws-cli-reject-my-iam-arn-for-not-matching-the-regex-pattern

**Comment by jagadeesh123-alt** [comment]
> * AWSLambdaBasicExecutionRole

where to add this two things

**Comment by meritz** [comment]
tks
