### ISSUE TITLE
Template builds inappropriate resources into zip by misapplying lists of downstream resources

### ISSUE THREAD

**Issue by StoneCypher** [motdotla/node-lambda-template#12]
Default project builds dependencies of node-lambda into lambda zipfile. Hello world now carries `commander`, `graceful-readlink`, `sax`, `xml2js`, `xmlbuilder`, etc. ~771k of deps.

New project maintainer closed the original #4 because he misunderstands it.  I was trying to explain but he locked the issue because I asked him to not close it.

The actual problem is not that `node-lambda` builds things in because they're in use; it's that `node-lambda-template` is incorrectly propositioning its own tools as part of the downstream build.

This is a problem in the template, despite that the new maintainer closed an issue while the issue's creator was trying to explain what they misunderstood.

@motdotla - please help with the overly aggressive new issue burying mod, thanks

**Comment by StoneCypher** [comment]
Unfortunately new maintainer is using issue locking when someone says "please don't close things that aren't fixed just because you don't want to learn about them"

I guess this isn't a safe project for me anymore

**Comment by DeviaVir** [comment]
To me, your request is still very vague, but I would like clear visibility on the issue you've apparently identified.

Just to confirm, the change you would like to see is `node-lambda` removed as a dependency from the `package.json`, and instead inform the user to do an `npm install -g node-lambda` and run the commands using the global bin vs. having it use the `node-modules` here?

If my assumption above is incorrect, please add a concise and clear description of the problem.

**Comment by StoneCypher** [comment]
I'm not sure what you find vague, unclear or imprecise about "you're building things into the deployed bundle that the deployed bundle doesn't want or need"

1) Make a `hello, world` 
2) Build the `hello, world`
3) Notice that inside the package to be deployed to `lambda`, there are references to things not used by the `hello, world`
4) Notice that this is a direct result of the way the template sets up the parent library

The problem is not in the outside.  It is that the built package is listing the build tools as dependencies.

The thing that goes to `lambda` does not have any need of `node-lambda`

**Comment by DeviaVir** [comment]
resolved in https://github.com/motdotla/node-lambda-template/pull/14

**Comment by StoneCypher** [comment]
thank you

**Comment by DeviaVir** [comment]
@StoneCypher no, thank you. I apologise for the way I handled your first ticket and am very happy you were persistent with this problem.
