### ISSUE TITLE
Update to package.json to latest version of node-lambda.

### ISSUE THREAD

**Issue by nodanaonlyzuul** [motdotla/node-lambda-template#9]
Hi.

Firstly - thanks for the awesome repo.
I see there are a few PRs piling up regarding updating the version of `node-lambda` referenced
in `package.json`.

* https://github.com/motdotla/node-lambda-template/pull/5 (requesting bump to `^0.7.1`)
* https://github.com/motdotla/node-lambda-template/pull/8 (requesting bump to `0.1.5`)

As of my writing, the current version is 0.8.13, which obviates both PRs.

So - I'm hoping this issue can be a stand-in to update to _latest_, whatever it is when you take on the work.  Since this app is a many people's first brush with using `node-lambda`, it would be nice if running `node-lambda setup` wrote the newest version of `.env`.

Thanks again for your work.

**Comment by DeviaVir** [comment]
https://github.com/motdotla/node-lambda-template/pull/11
